#Boolean practice
print('\n1----------')
print(True and True)
print('\n2----------')
print(False and True)
print('\n3----------')
print(1==1 and 2==1)
print('\n4----------')
print('test'=='testing')
print('\n5----------')
print(1==1 or 2!=1)
print('\n6----------')
print(True and 1==1)
print('\n7----------')
print(False and 0!=0)
print('\n8----------')
print(True or 1 ==1)
print('\n9----------')
print('test' == 'testing')
print('\n10----------')
print(1 != 0 and 2 == 1)
print('\n11----------')
print('test' != 'testing')
print('\n12----------')
print('test' == 1)
print('\n13----------')
print(not(True and False))
print('\n14----------')
print(not(1==1 and 0!=1))
print('\n15----------')
print(not(10==1 or 1000==1000))
print('\n16----------')
print(not(1!=10 or 3 ==4))
print('\n17----------')
print(not('testing' == 'testing' and 'Zed' == 'cool kid'))
print('\n18----------')
print(1==1 and not('testing' == 1 or 1 == 0))
print('\n19----------')
print('chunky' == 'bacon' and (not(3==4 or 3==3)))
print('\n20----------')
print(3==3 and (not('testing'=='testing' or 'Python' == 'fun')))